# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import requests
import os

# Raw URL del archivo CSV en GitHub
csv_url = 'https://raw.githubusercontent.com/rz-i/udea-0311152-01-nubosidad/963f658720f1258016cb6eb3b5693ee7e6729815/data/segmented_metrics_cleaned.csv'
local_dir = './data'
local_csv_path = os.path.join(local_dir, 'segmented_metrics_cleaned.csv')

# Crear el directorio local si no existe
os.makedirs(local_dir, exist_ok=True)

print(f"Descargando CSV desde: {csv_url}")
print(f"Guardando en: {local_csv_path}")

try:
    response = requests.get(csv_url)
    response.raise_for_status()  # Lanza un error para códigos de estado HTTP incorrectos (4xx o 5xx)

    with open(local_csv_path, 'wb') as f:
        f.write(response.content)
    print("Archivo CSV descargado exitosamente.")

    # Cargar el archivo CSV en un DataFrame de Pandas
    df = pd.read_csv(local_csv_path)
    print("Archivo CSV cargado en un DataFrame.")

    # Mostrar las primeras 5 filas del DataFrame
    print("Primeras 5 filas del DataFrame:")
    display(df.head())

except requests.exceptions.RequestException as e:
    print(f"Error al descargar el archivo CSV: {e}")
except pd.errors.EmptyDataError:
    print("El archivo CSV está vacío o no contiene datos.")
except Exception as e:
    print(f"Ocurrió un error: {e}")

def clean_and_merge(df):
    print(f"Initial DataFrame shape: {df.shape}")

    # 1. Remove exact duplicate rows
    df.drop_duplicates(inplace=True)
    print(f"DataFrame shape after removing duplicates: {df.shape}")

    # 2. Filter out rows with mask_pixel_count below a minimum threshold
    min_mask_pixel_count_threshold = 100 # A common starting point
    df = df[df['mask_pixel_count'] >= min_mask_pixel_count_threshold]
    print(f"DataFrame shape after filtering low mask pixel count (<{min_mask_pixel_count_threshold}): {df.shape}")

    # 3. Implement outlier filtering for 'mean_index', 'std_dev', and 'mask_pixel_count'
    columns_for_outlier_filtering = ['mean_index', 'std_dev', 'mask_pixel_count']

    for col in columns_for_outlier_filtering:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
        print(f"DataFrame shape after filtering outliers for '{col}': {df.shape}")

    return df

# Call the function with the df DataFrame and assign the returned cleaned DataFrame back to df
df = clean_and_merge(df)

# Display the shape of the cleaned DataFrame and its first 5 rows
print("\nShape of the cleaned DataFrame:", df.shape)
print("\nFirst 5 rows of the cleaned DataFrame:")
display(df.head())

columns_for_stats = ['mean_index', 'std_dev', 'mask_pixel_count']
descriptive_stats = df[columns_for_stats].describe()
print("Estadísticas Descriptivas para las columnas clave:")
display(descriptive_stats)

import seaborn as sns
import matplotlib.pyplot as plt

print("Libraries `seaborn` and `matplotlib.pyplot` imported.")

"""En esta grafica se compara el Mean Index que es la intensidad o tipo de nubosidad frente a la direccion que nos muestra el movimiento de la nube.

En este diagrama de cajas podemos ver como fue el comportamiento de las nubes para cada punto cardinal.

Si la linea está mas hacia arriba nos muestra que tan opaca estuvo la nube, pero si estan todas  muy es similares, significa que el cielo estuvo uniforme, en este caso saco como concusión que el cielo estuvo muy similar, de forma opaca.

El grosor de la caja nos dice que tan similar fueron  las nubes en esa direccion, cajas anchas son  nubes muy variables, cajas cortas nubes muy similares.

La linea media nos dice hacia donde tienden a ir todos los datos, pero si la linea está muy por debajo de la caja significa que hay valores que estiran la caja, esos son algunos sesgos.

"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='direction', y='mean_index', data=df)
plt.xlabel('Dirección')
plt.ylabel('Mean Index')
plt.title('Distribución del Mean Index por Dirección')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""En esta grafica podremos opservar una relacion entre dias y Mean index, por lo que se verá como varian las nubes dia tras dias.

si hay picos es por que las nubes son opacas, si hay valles es porque hay nubes claras, si todos los picos suben a la vez, porque hubo un paso de nubes muy marcado en toda la ciudad o una nubocidad amplia.

Podemos analizar que dias hubo menos nubes y que dia hubieron mas nubes.

Si hay muchos picos y valles significa, movimiento de muchas nubes a lo largo de los dias, posiblemente comulos.

Notemos que la tendencia global es hacia nubes claras no muy cargadas de agua, tienden a ser nubes o muy altas o de media altura

"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Asegurar orden y formato
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values(by='timestamp')

plt.figure(figsize=(14, 7))

# 1. Graficar los datos originales (las líneas de cada dirección)
sns.lineplot(x='timestamp', y='mean_index', hue='direction', data=df, marker='o', errorbar=None, alpha=0.6)

# 2. CALCULAR LA TENDENCIA GLOBAL
# Convertimos fechas a números para que la matemática funcione
x_numeric = mdates.date2num(df['timestamp'])
y = df['mean_index']

# Ajuste lineal: y = mx + b (polinomio de grado 1)
z = np.polyfit(x_numeric, y, 1)
p = np.poly1d(z)

# 3. Dibujar la línea de tendencia sobre el gráfico
plt.plot(df['timestamp'], p(x_numeric), color="red", linewidth=3, linestyle="--", label='Tendencia Global')

# Configuración estética
plt.title('Tendencia Temporal del Mean Index por Dirección con Línea de Tendencia Global')
plt.xlabel('Fecha y Hora')
plt.ylabel('Mean Index')
plt.legend(title='Dirección / Tendencia')
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Mapa de calor.

Los colores nos dan informacion,

Rojo: significa una relación directa
Azul: Inversa

mask_pixel_count = Tamaño de la nube
mena index = Opacidad de la nube

En la relacion de estos dos se encontro que son nubes pequeñas pero birllantes o grandes pero muy tenues

mean_index vs std_dev:

las nubes son de color muy plano y uniforme


"""

columns_for_correlation = ['mean_index', 'std_dev', 'mask_pixel_count']
correlation_matrix = df[columns_for_correlation].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Matriz de Correlación entre Métricas Clave')
plt.show()

"""Una unica montaña nos muestra la consistencia de los datos, nubes todas muy similares, notemos que la grafica tira un poco mas hacia un index mas hacia la izquierda nubes mayoritariamente nubado.

"""

plt.figure(figsize=(10, 6))
sns.histplot(df['mean_index'], kde=True, bins=20, color='skyblue')
plt.xlabel('Mean Index')
plt.ylabel('Frecuencia')
plt.title('Distribución del Mean Index')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

from sklearn.preprocessing import StandardScaler

# 2. Definir una lista de las columnas que se utilizarán para el clustering
columns_for_clustering = ['mean_index', 'std_dev', 'mask_pixel_count']

# 3. Crear un nuevo DataFrame (df_clustering) con solo estas columnas seleccionadas
df_clustering = df[columns_for_clustering].copy()

# 4. Instanciar un objeto StandardScaler
scaler = StandardScaler()

# 5. Ajustar el escalador a los datos en df_clustering y transformar los datos
scaled_features = scaler.fit_transform(df_clustering)

# 6. Convertir los scaled_features resultantes en un DataFrame de Pandas
df_scaled = pd.DataFrame(scaled_features, columns=columns_for_clustering)

print("DataFrame de características escaladas (primeras 5 filas):")
display(df_scaled.head())

"""## Determinación del Número Óptimo de Clusters (Método del Codo)



"""

from sklearn.cluster import KMeans

print("KMeans imported successfully.")

wcss = []
max_k = 10 # Example range, adjust as needed

for i in range(1, max_k + 1):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init='auto')
    kmeans.fit(df_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(range(1, max_k + 1), wcss, marker='o', linestyle='--')
plt.xlabel('Número de Clusters (k)')
plt.ylabel('WCSS (Suma de Cuadrados Intra-Cluster)')
plt.title('Método del Codo para K-Means')
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(range(1, max_k + 1))
plt.show()

print("Gráfico del Método del Codo generado con éxito. Examine el gráfico para identificar el número óptimo de clusters.")

optimal_k = 3 # Based on the elbow method plot, where the rate of decrease in WCSS significantly slows down.

kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init='auto')
kmeans.fit(df_scaled)

df['cluster_label'] = kmeans.labels_

print(f"K-Means clustering applied with {optimal_k} clusters.")
print("Primeras 5 filas del DataFrame con las etiquetas de cluster:")
display(df.head())

from sklearn.decomposition import PCA

print("PCA imported successfully.")

"""En este cluster encontramos tres grupos, de los cuales podemos encontrar que las nubes mas densas o grandes están hacia la derecha, mientras que los puntos mas altos son nubes mas irregulares.

Cluster 0 (Cielo Limpio/Ralo): Puntos agrupados en un extremo. Son momentos con pocos píxeles de nube y brillo bajo.

Cluster 1 (Nubosidad Fragmentada): Nubes medianas, quizás con mucha textura (cúmulos). Están en el centro de la gráfica.

Cluster 2 (Cielo Cubierto/Denso): Puntos en el otro extremo. Representan grandes masas nubosas muy uniformes y brillantes.


"""

pca = PCA(n_components=2)
pca_features = pca.fit_transform(df_scaled)

df_pca = pd.DataFrame(data=pca_features, columns=['PC1', 'PC2'])
df_pca['cluster_label'] = df['cluster_label'].reset_index(drop=True)

plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='PC1', y='PC2', hue='cluster_label', data=df_pca,
    palette='viridis', s=100, alpha=0.8
)
plt.title('Visualización de Clusters (PCA 2D)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Cluster')
plt.show()